function init(self)
	msg.post(".", "acquire_input_focus")

	timer.delay(1, true, function()
		factory.create("#factory")
		sound.play("#blub")
	end)
end
function on_input(self, action_id, action)
	if action_id == hash("down") then
		local pos = go.get_position()
		pos.y = pos.y - 10
		go.set_position(pos)
	elseif action_id == hash("up") then
		local pos = go.get_position()
		pos.y = pos.y + 10
		go.set_position(pos)
	end
end